### ISSUE TITLE
ERROR [139625889173184] [TensorRT] 3: [runtime.cpp::~Runtime::346] Error Code 3: API Usage Error (Parameter check failed at: runtime/rt/runtime.cpp::~Runtime::346, condition: mEngineCounter.use_count() == 1. Destroying a runtime before destroying deserialized engines created by the runtime leads to undefined behavior.

### ISSUE THREAD

**Issue by Czzh1** [AICAN-Research/H2G-Net#3] opened 2024-03-24 03:33 UTC
When I ran the pipeline at the seconde time， the problem was happened！

**Comment by andreped** [comment] 2024-03-24 09:23
I assume you ran the CLI twice, @Czzh1? Any thoughts on how to resolve this issue, @smistad, as it looks like a FAST bug? Perhaps simply upgrading to a newer `pyFAST` version would resolve it?

**Comment by andreped** [comment] 2024-06-14 23:03
@Czzh1 Did you manage to resolve the issue?

**Comment by andreped** [comment] 2024-08-09 09:55
As I am unable to reproduce this and there is no more information, I am closing this issue. Feel free to reopen or open a new ticket if you are still experiencing issues!

**Closed by andreped** 2024-08-09 09:55 UTC
Labels: bug
